name: CI

on:
  push:
    branches: [main]
    paths: ["app/**", ".github/workflows/**"]
  pull_request:
    branches: [main]
    paths: ["app/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REPOSITORY_NAME: el2arb3a-project
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run type checking
        run: bun run check

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Build Docker Image
        run: docker build -t ${{ vars.ECR_REGISTRY }}/${{ env.REPOSITORY_NAME }}:latest .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.ECR_REGISTRY }}/${{ env.REPOSITORY_NAME }}:latest
          format: table
          exit-code: 0 # Don't fail the build on vulnerabilities, but log them
          severity: CRITICAL,HIGH

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::439328746854:role/terraform-el2arb3a
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Image to Amazon ECR
        run: docker push ${{ vars.ECR_REGISTRY }}/${{ env.REPOSITORY_NAME }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ matrix.ecs_service }} \
            --task-definition ${{ steps.register.outputs.arn }} \
            --force-new-deployment
